// Generated by gencpp from file ping360_sonar/SonarEcho.msg
// DO NOT EDIT!


#ifndef PING360_SONAR_MESSAGE_SONARECHO_H
#define PING360_SONAR_MESSAGE_SONARECHO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ping360_sonar
{
template <class ContainerAllocator>
struct SonarEcho_
{
  typedef SonarEcho_<ContainerAllocator> Type;

  SonarEcho_()
    : header()
    , angle(0.0)
    , gain(0)
    , number_of_samples(0)
    , transmit_frequency(0)
    , speed_of_sound(0)
    , range(0)
    , intensities()  {
    }
  SonarEcho_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle(0.0)
    , gain(0)
    , number_of_samples(0)
    , transmit_frequency(0)
    , speed_of_sound(0)
    , range(0)
    , intensities(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _gain_type;
  _gain_type gain;

   typedef uint16_t _number_of_samples_type;
  _number_of_samples_type number_of_samples;

   typedef uint16_t _transmit_frequency_type;
  _transmit_frequency_type transmit_frequency;

   typedef uint16_t _speed_of_sound_type;
  _speed_of_sound_type speed_of_sound;

   typedef uint8_t _range_type;
  _range_type range;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _intensities_type;
  _intensities_type intensities;





  typedef boost::shared_ptr< ::ping360_sonar::SonarEcho_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ping360_sonar::SonarEcho_<ContainerAllocator> const> ConstPtr;

}; // struct SonarEcho_

typedef ::ping360_sonar::SonarEcho_<std::allocator<void> > SonarEcho;

typedef boost::shared_ptr< ::ping360_sonar::SonarEcho > SonarEchoPtr;
typedef boost::shared_ptr< ::ping360_sonar::SonarEcho const> SonarEchoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ping360_sonar::SonarEcho_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ping360_sonar::SonarEcho_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ping360_sonar::SonarEcho_<ContainerAllocator1> & lhs, const ::ping360_sonar::SonarEcho_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle == rhs.angle &&
    lhs.gain == rhs.gain &&
    lhs.number_of_samples == rhs.number_of_samples &&
    lhs.transmit_frequency == rhs.transmit_frequency &&
    lhs.speed_of_sound == rhs.speed_of_sound &&
    lhs.range == rhs.range &&
    lhs.intensities == rhs.intensities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ping360_sonar::SonarEcho_<ContainerAllocator1> & lhs, const ::ping360_sonar::SonarEcho_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ping360_sonar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping360_sonar::SonarEcho_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping360_sonar::SonarEcho_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping360_sonar::SonarEcho_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a4e4ed79c9e54919e2ef7e62c1eb5e";
  }

  static const char* value(const ::ping360_sonar::SonarEcho_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a4e4ed79c9e549ULL;
  static const uint64_t static_value2 = 0x19e2ef7e62c1eb5eULL;
};

template<class ContainerAllocator>
struct DataType< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ping360_sonar/SonarEcho";
  }

  static const char* value(const ::ping360_sonar::SonarEcho_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header            #header info\n"
"float32 angle               # the measurement angle [rad]\n"
"uint8 gain  # Sonar Gain\n"
"uint16 number_of_samples \n"
"uint16 transmit_frequency # [kHz]\n"
"uint16 speed_of_sound # [m/s]\n"
"uint8 range      #  range value [m]\n"
"uint8[] intensities    # intensity data [0-255].  This is the actual data received from the sonar\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ping360_sonar::SonarEcho_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle);
      stream.next(m.gain);
      stream.next(m.number_of_samples);
      stream.next(m.transmit_frequency);
      stream.next(m.speed_of_sound);
      stream.next(m.range);
      stream.next(m.intensities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonarEcho_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ping360_sonar::SonarEcho_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ping360_sonar::SonarEcho_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "gain: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gain);
    s << indent << "number_of_samples: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.number_of_samples);
    s << indent << "transmit_frequency: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.transmit_frequency);
    s << indent << "speed_of_sound: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.speed_of_sound);
    s << indent << "range: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.range);
    s << indent << "intensities[]" << std::endl;
    for (size_t i = 0; i < v.intensities.size(); ++i)
    {
      s << indent << "  intensities[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.intensities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PING360_SONAR_MESSAGE_SONARECHO_H
